// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './test/fixture';
import * as fixture1 from './src/screens/main/Main.fixture';
import * as fixture2 from './src/screens/discount/Discount.fixture';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:5001",
  "rendererUrl": null
};

const fixtures = {
  'test/fixture.ts': { module: fixture0 },
  'src/screens/main/Main.fixture.tsx': { module: fixture1 },
  'src/screens/discount/Discount.fixture.tsx': { module: fixture2 }
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
